# [[plugin.deps]]
# use = "gclarkjr5/gitui"
# rev = "397e9cf"
# hash = "70d6eec6166d03118e4d9576473779a6"

[[plugin.deps]]
use = "yazi-rs/plugins:mime-ext"
rev = "864a021"
hash = "5e24c167e9ae9a203a48f2a438b8c705"

# [[plugin.deps]]
# use = "GrzegorzKozub/mdcat"
# rev = "7b7380a"
# hash = "40c20e6c1085d1f45309b9f148bf4f6e"

[[plugin.deps]]
use = "yazi-rs/plugins:smart-enter"
rev = "864a021"
hash = "7918aab6a71caf31b58411f789195677"

[[plugin.deps]]
use = "yazi-rs/plugins:toggle-pane"
rev = "864a021"
hash = "f3853bbdd1da2fad09d059ab5464abfd"

[[plugin.deps]]
use = "Rolv-Apneseth/starship"
rev = "6fde3b2"
hash = "7ddb7a790746fd91ecdd0350cc5a5d8c"

[[plugin.deps]]
use = "yazi-rs/plugins:full-border"
rev = "864a021"
hash = "1f3dad061209081a6b04dd6ff2cb06c7"

[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"
rev = "864a021"
hash = "f0c4b41b5d19a3144958383333eff6e7"

[[plugin.deps]]
use = "yazi-rs/plugins:vcs-files"
rev = "864a021"
hash = "36405f8781fcaf33ceab24dffd5cea19"

[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "cbc4450"
hash = "a57f09c9e61ffc850d8ea8c6fc1efb2c"

[[plugin.deps]]
use = "wylie102/duckdb"
rev = "3f8c863"
hash = "87b9233a74325e95011670ed20bbd0d4"

[flavor]
deps = []
